---
name: "pipeline"
description: "A workflow that can be used as a pipeline for Terraform execution"
enabled: true
entry_point: "workflows/pipeline.yaml"

runner_type: "orquesta"

parameters:
  backend:
    type: "object"
    description: "Key-Value pairs of backend configuration options."
    required: false
  plan_path:
    type: "string"
    description: "path of the Terraform files"
    required: true
  terraform_exec:
    type: "string"
    description: "path of the Terraform bin"
    required: false
  variable_dict:
    type: "object"
    description: "Terraform variable object (variables in here will overwrite any that are in files)"
    required: false
  variable_files:
    type: "array"
    description: "Terraform variable files"
    required: false
  workspace:
    type: "string"
    description: "The name of the Terraform workspace to use."
    default: "default"
    required: false
  destroy:
    type: boolean
    description: "Used if we want to run a destroy operation"
    required: false
